version: "3.8"
services:
  test_db:
    container_name: "test-db"
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5429:5432"

  redis:
    image: redis:7
    container_name: redis
    environment:
      - REDIS_URL=redis://localhost:6379
    ports:
      - 6379:6379

volumes:
  cms_app:
