version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  test-db:
    container_name: "test-db"
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cms_db
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379


volumes:
    cms_app:

